name: Github Actions Clock Bot

on:
    push:
    schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v2
    
      - name: Run
        run: chmod +x ./clock.sh
            ./clock.sh
