name: Github Actions Clock Bot

on:
  push:
  schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check
      - uses: actions/checkout@v2
        
      - name: Set
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Run
        run: bash./clock.py
